# Example ArgoCD values file
global:
  image:
    repository: argoproj/argocd
    tag: v2.1.4
server:
  ingress:
    enabled: true
    hosts:
      - argocd-demo-cluster.292s.io
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: "letsencrypt-staging" # Use your own issuer if needed
